### ISSUE TITLE
Can't import the App #1

### ISSUE THREAD

**Issue by Roodmack** [misskristine94/NeumorphicUIKitSilver#1]
Hi,

First of all thank you sharing,
i have an issue when i try to import the app
i try different way : Solution, App Package, Component
still get an error !

can you please check it, or release it in a unmanage solution

Best regards,

**Comment by Roodmack** [comment]
The main Issue i imported the full repository instead of the app !
just importe it the correct way and bingooooooo
thank you for your help ! 

![image](https://user-images.githubusercontent.com/96177590/179361690-3816448f-65d1-4671-b1b1-c13a2e6fae20.png)

**Comment by kristinekolodziejski** [comment]
You're very welcome @Roodmack!! Hope you enjoy using the kit 😊
